name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 安装 Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ 打包 release APK
      - name: Build APK
        run: flutter build apk --release

      # 5️⃣ 上传 APK 到 workflow artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk